dist: trusty
sudo: false
language: node_js
node_js:
  - "6"
addons:
  sonarqube:
    organization: "LaCarte"
    token:
      secure: "$SONAR_TOKEN"
branches:
  only:
  - master
  - andre
script:
  - sonar-scanner 
  
#notifications:
#slack: 
